### ISSUE TITLE
http response code

### ISSUE THREAD

**Issue by kscheirer** [lucius-digital/anonymous_redirect#1]
Hi! I think you should not use a 301 response code, this is for a "Permanent Redirect", some browsers may cache this since you are saying the resource has moved permanently.

Instead a [302 or 307](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection) is a temporary redirect for just this one time.

https://github.com/lucius-digital/anonymous_redirect/blob/85a10d61de53c8938e89dbe85fe383caaa73f944/src/EventSubscriber/AnonymousRedirectSubscriber.php#L38

**Comment by kscheirer** [comment]
In https://www.drupal.org/project/anonymous_login/issues/3151192 they said the opposite, so maybe 301 is  the right answer? Still seems odd to me.

**Comment by jorislucius** [comment]
Thanks, I get it, but I guess people have to decide what's best for their project.
